# Cloud Build para desplegar directamente a Cloud Run
# Cabañas el Encanto del Edén - Solo Producción

steps:
  # Paso 1: Instalar dependencias
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    id: 'install-deps'

  # Paso 2: Construir la imagen Docker (sin linting para deploy más rápido)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cabanas-eden/website:$BUILD_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cabanas-eden/website:latest',
      '.'
    ]
    id: 'build-image'
    waitFor: ['install-deps']

  # Paso 3: Subir imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cabanas-eden/website:$BUILD_ID']
    id: 'push-image'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cabanas-eden/website:latest']
    id: 'push-latest'
    waitFor: ['build-image']

  # Paso 4: Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy cabanas-eden-website \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/cabanas-eden/website:$BUILD_ID \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --set-env-vars="NODE_ENV=production,VITE_WHATSAPP_NUMBER=573209063849,VITE_EMAIL=reservascabanaseleden@gmail.com" \
          --timeout=300 \
          --quiet
    id: 'deploy-cloudrun'
    waitFor: ['push-image']

  # Paso 5: Mostrar URL y confirmar deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🏔️ ¡Cabañas el Encanto del Edén desplegado con éxito!"
        SERVICE_URL=$(gcloud run services describe cabanas-eden-website --region=us-central1 --format="value(status.url)")
        echo "🌐 Tu sitio web está disponible en: $SERVICE_URL"
        echo "📱 Comparte esta URL con tus clientes"
        echo "⏱️ Deploy completado en: $(date)"
    id: 'show-success'
    waitFor: ['deploy-cloudrun']

# Configuración optimizada para deployment rápido
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'NODE_ENV=production'

# 8 minutos máximo
timeout: '480s'

tags:
  - 'cabanas-eden'
  - 'production'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cabanas-eden/website:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cabanas-eden/website:latest'